# Generated by Django 2.2.8 on 2020-07-17 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='\\images'),
            preserve_default=False,
        ),
    ]
